/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiKeysGetMe } from "../funcs/api-keys-get-me.js";
import { apiKeysOauthAuthorize } from "../funcs/api-keys-oauth-authorize.js";
import { apiKeysOauthJwks } from "../funcs/api-keys-oauth-jwks.js";
import { apiKeysOauthRevoke } from "../funcs/api-keys-oauth-revoke.js";
import { apiKeysOauthToken } from "../funcs/api-keys-oauth-token.js";
import { apiKeysRotateAPIKey } from "../funcs/api-keys-rotate-api-key.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class APIKeys extends ClientSDK {
  /**
   * Get current API key + workspace
   *
   * @remarks
   * Returns the workspace and API key metadata for the calling key.
   */
  async getMe(
    options?: RequestOptions,
  ): Promise<operations.GetMeResponse> {
    return unwrapAsync(apiKeysGetMe(
      this,
      options,
    ));
  }

  /**
   * Rotate an API key
   *
   * @remarks
   * Issues a new key value for the given key id. The old key is scheduled
   * for expiry; the response includes the new plaintext (returned exactly
   * once) and the old key's expiry timestamp.
   */
  async rotateApiKey(
    request: operations.RotateApiKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.RotateApiKeyResponse> {
    return unwrapAsync(apiKeysRotateAPIKey(
      this,
      request,
      options,
    ));
  }

  /**
   * Begin OAuth 2.0 PKCE authorization
   *
   * @remarks
   * Authorization endpoint for the PKCE-only flow. Validates the request
   * and redirects the user-agent to the consent screen.
   */
  async oauthAuthorize(
    request: operations.OauthAuthorizeRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(apiKeysOauthAuthorize(
      this,
      request,
      options,
    ));
  }

  /**
   * Exchange authorization code or refresh token for an access token
   *
   * @remarks
   * Token endpoint. Accepts `authorization_code` (after PKCE) or
   * `refresh_token` grants. Returns a JWT access token bound to the
   * granting workspace and the requested scopes.
   */
  async oauthToken(
    request: operations.OauthTokenRequest,
    options?: RequestOptions,
  ): Promise<operations.OauthTokenResponse> {
    return unwrapAsync(apiKeysOauthToken(
      this,
      request,
      options,
    ));
  }

  /**
   * Revoke an OAuth access or refresh token
   *
   * @remarks
   * Idempotent revocation. Returns 200 whether or not the token was
   * previously valid (per RFC 7009).
   */
  async oauthRevoke(
    request: operations.OauthRevokeRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(apiKeysOauthRevoke(
      this,
      request,
      options,
    ));
  }

  /**
   * JSON Web Key Set for OAuth access token verification
   *
   * @remarks
   * Public JWKS used by clients/resource servers to verify access-token
   * signatures. Cached aggressively; rotated infrequently.
   */
  async oauthJwks(
    options?: RequestOptions,
  ): Promise<{ [k: string]: any }> {
    return unwrapAsync(apiKeysOauthJwks(
      this,
      options,
    ));
  }
}
