/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { charactersCreateCharacter } from "../funcs/characters-create-character.js";
import { charactersDeleteCharacter } from "../funcs/characters-delete-character.js";
import { charactersGetCharacter } from "../funcs/characters-get-character.js";
import { charactersListCharacters } from "../funcs/characters-list-characters.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Characters extends ClientSDK {
  /**
   * Create + train a custom character from reference images
   *
   * @remarks
   * Creates a character card and queues a training job. Returns a Job
   * descriptor (status `queued`) plus the new `character_id`. Poll
   * `/v1/jobs/{id}` for completion. Wallet is charged at the
   * `char.train_soul` rate.
   */
  async createCharacter(
    request: operations.CreateCharacterRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateCharacterResponse> {
    return unwrapAsync(charactersCreateCharacter(
      this,
      request,
      options,
    ));
  }

  /**
   * List workspace characters (cursor-paginated)
   *
   * @remarks
   * Cursor-paginated list of characters in the calling workspace. Soft-deleted rows are excluded.
   */
  async listCharacters(
    request?: operations.ListCharactersRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListCharactersResponse> {
    return unwrapAsync(charactersListCharacters(
      this,
      request,
      options,
    ));
  }

  /**
   * Fetch a single character
   *
   * @remarks
   * Returns a single character. 404 (not 403) for cross-workspace ids so existence is never leaked.
   */
  async getCharacter(
    request: operations.GetCharacterRequest,
    options?: RequestOptions,
  ): Promise<models.Character> {
    return unwrapAsync(charactersGetCharacter(
      this,
      request,
      options,
    ));
  }

  /**
   * Soft-delete a character
   *
   * @remarks
   * Requires `admin` scope. Returns 204 with no body.
   */
  async deleteCharacter(
    request: operations.DeleteCharacterRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(charactersDeleteCharacter(
      this,
      request,
      options,
    ));
  }
}
