/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { discoveryEstimateGeneration } from "../funcs/discovery-estimate-generation.js";
import { discoveryGetOpenApiSpec } from "../funcs/discovery-get-open-api-spec.js";
import { discoveryGetPricing } from "../funcs/discovery-get-pricing.js";
import { discoveryListModels } from "../funcs/discovery-list-models.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Discovery extends ClientSDK {
  /**
   * Fetch the AERIOX OpenAPI 3.1 spec as JSON
   *
   * @remarks
   * Returns the canonical OpenAPI 3.1 document for the AERIOX public API
   * as JSON. The spec is also available as YAML at
   * `docs/api/aeriox.openapi.yaml` in the source repo. Public — no
   * authentication required. Cached at the edge for one hour.
   */
  async getOpenApiSpec(
    options?: RequestOptions,
  ): Promise<{ [k: string]: any }> {
    return unwrapAsync(discoveryGetOpenApiSpec(
      this,
      options,
    ));
  }

  /**
   * Get USD price list for all operations
   *
   * @remarks
   * Public endpoint — no authentication required.
   */
  async getPricing(
    options?: RequestOptions,
  ): Promise<operations.GetPricingResponse> {
    return unwrapAsync(discoveryGetPricing(
      this,
      options,
    ));
  }

  /**
   * Estimate cost and feasibility for a generation
   *
   * @remarks
   * Returns credit + USD cost, p95 wall-clock estimate, and a feasibility
   * check (`would_succeed`) with structured `reasons_blocked`. Does not
   * commit funds or call upstream providers.
   */
  async estimateGeneration(
    request: operations.EstimateGenerationRequest,
    options?: RequestOptions,
  ): Promise<operations.EstimateGenerationResponse> {
    return unwrapAsync(discoveryEstimateGeneration(
      this,
      request,
      options,
    ));
  }

  /**
   * Capability + price catalog for every supported model
   *
   * @remarks
   * Returns every active model in the cost spine with capabilities (max resolution, duration, audio support) and per-unit USD pricing.
   */
  async listModels(
    options?: RequestOptions,
  ): Promise<operations.ListModelsResponse> {
    return unwrapAsync(discoveryListModels(
      this,
      options,
    ));
  }
}
