/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { generationComposeVideo } from "../funcs/generation-compose-video.js";
import { generationCreateGeneration } from "../funcs/generation-create-generation.js";
import { generationCreateNode } from "../funcs/generation-create-node.js";
import { generationDeleteNode } from "../funcs/generation-delete-node.js";
import { generationGenerateAudio } from "../funcs/generation-generate-audio.js";
import { generationGenerateImage } from "../funcs/generation-generate-image.js";
import { generationGenerateVideo } from "../funcs/generation-generate-video.js";
import { generationGetNode } from "../funcs/generation-get-node.js";
import { generationListNodes } from "../funcs/generation-list-nodes.js";
import { generationRenderCard } from "../funcs/generation-render-card.js";
import { generationSearchCards } from "../funcs/generation-search-cards.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Generation extends ClientSDK {
  /**
   * Generate an image
   *
   * @remarks
   * Canonical image generation endpoint. Returns a queued job; clients
   * poll `/v1/generations/{id}` for status and asset URLs.
   */
  async generateImage(
    request: models.GenerateImageRequest,
    options?: RequestOptions,
  ): Promise<operations.GenerateImageResponse> {
    return unwrapAsync(generationGenerateImage(
      this,
      request,
      options,
    ));
  }

  /**
   * Generate a video
   *
   * @remarks
   * Canonical video generation endpoint. Returns a queued job; clients
   * poll `/v1/generations/{id}` for status and asset URLs.
   */
  async generateVideo(
    request: models.GenerateVideoRequest,
    options?: RequestOptions,
  ): Promise<operations.GenerateVideoResponse> {
    return unwrapAsync(generationGenerateVideo(
      this,
      request,
      options,
    ));
  }

  /**
   * Generate audio (text-to-speech)
   *
   * @remarks
   * Synthesize speech via ElevenLabs. Audio synthesis is fast enough
   * to be sync — returns a completed job inline with the audio URL.
   */
  async generateAudio(
    request: models.GenerateAudioRequest,
    options?: RequestOptions,
  ): Promise<operations.GenerateAudioResponse> {
    return unwrapAsync(generationGenerateAudio(
      this,
      request,
      options,
    ));
  }

  /**
   * Stitch multiple assets into a single video
   *
   * @remarks
   * Multi-shot video composition. Takes asset references and segment
   * timing, returns a queued composition job. Phase 3 ships the wallet
   * + concurrency contract; dispatch implementation lands Phase 4
   * (returns 501 with refund until then).
   */
  async composeVideo(
    request: models.ComposeRequest,
    options?: RequestOptions,
  ): Promise<operations.ComposeVideoResponse> {
    return unwrapAsync(generationComposeVideo(
      this,
      request,
      options,
    ));
  }

  /**
   * (Deprecated) Submit a generation job
   *
   * @remarks
   * Legacy generation endpoint. Deprecated alias of `/v1/images/generate`
   * (and video equivalents). Returns a queued job; clients poll
   * `/v1/generations/{id}`.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async createGeneration(
    request: operations.CreateGenerationRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateGenerationResponse> {
    return unwrapAsync(generationCreateGeneration(
      this,
      request,
      options,
    ));
  }

  /**
   * List cards (legacy `nodes` alias)
   *
   * @remarks
   * Backward-compat alias for `/v1/cards`. Response is dual-emitted with
   * both `nodes` and `cards` keys referencing the same array. Sunsets
   * on 2026-10-22.
   */
  async listNodes(
    request?: operations.ListNodesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListNodesResponse> {
    return unwrapAsync(generationListNodes(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a card (legacy `nodes` alias)
   *
   * @remarks
   * Backward-compat alias for `POST /v1/cards`. Request accepts either
   * `card_type` or legacy `node_type`. Response includes both `node` and
   * `card` fields referencing the same row.
   */
  async createNode(
    request: operations.CreateNodeRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateNodeResponse> {
    return unwrapAsync(generationCreateNode(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single card with outgoing edges
   */
  async getNode(
    request: operations.GetNodeRequest,
    options?: RequestOptions,
  ): Promise<operations.GetNodeResponse> {
    return unwrapAsync(generationGetNode(
      this,
      request,
      options,
    ));
  }

  /**
   * Soft-delete a card
   */
  async deleteNode(
    request: operations.DeleteNodeRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteNodeResponse> {
    return unwrapAsync(generationDeleteNode(
      this,
      request,
      options,
    ));
  }

  /**
   * Semantic search across the workspace card library
   *
   * @remarks
   * Voyage-embedding-backed similarity search over cards. Workspace-scoped.
   * Returns 503 when `VOYAGE_API_KEY` is not configured on the deployment.
   */
  async searchCards(
    request: operations.SearchCardsRequest,
    options?: RequestOptions,
  ): Promise<operations.SearchCardsResponse> {
    return unwrapAsync(generationSearchCards(
      this,
      request,
      options,
    ));
  }

  /**
   * Render a card's structured back-side payload
   *
   * @remarks
   * Returns the uniform `RenderedInputs` payload produced by the registered
   * renderer for the card's type — the same view the canvas executor uses
   * when wiring this card to a downstream node.
   */
  async renderCard(
    request: operations.RenderCardRequest,
    options?: RequestOptions,
  ): Promise<operations.RenderCardResponse> {
    return unwrapAsync(generationRenderCard(
      this,
      request,
      options,
    ));
  }
}
