/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { jobsCancelJob } from "../funcs/jobs-cancel-job.js";
import { jobsGetGeneration } from "../funcs/jobs-get-generation.js";
import { jobsGetJob } from "../funcs/jobs-get-job.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Jobs extends ClientSDK {
  /**
   * (Deprecated) Poll generation status
   *
   * @remarks
   * Deprecated alias of `/v1/jobs/{id}`. Workspace-scoped.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async getGeneration(
    request: operations.GetGenerationRequest,
    options?: RequestOptions,
  ): Promise<operations.GetGenerationResponse> {
    return unwrapAsync(jobsGetGeneration(
      this,
      request,
      options,
    ));
  }

  /**
   * Poll unified job status
   *
   * @remarks
   * Workspace-scoped read of a job's current state. Replaces `/v1/generations/{id}`.
   */
  async getJob(
    request: operations.GetJobRequest,
    options?: RequestOptions,
  ): Promise<models.Job> {
    return unwrapAsync(jobsGetJob(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel a queued or running job
   *
   * @remarks
   * Refunds any wallet reservation held by the job. Returns the job
   * in its new (cancelled) state. 409 if the job has already reached
   * a terminal state.
   */
  async cancelJob(
    request: operations.CancelJobRequest,
    options?: RequestOptions,
  ): Promise<models.Job> {
    return unwrapAsync(jobsCancelJob(
      this,
      request,
      options,
    ));
  }
}
