/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { prismsApplyPrism } from "../funcs/prisms-apply-prism.js";
import { prismsListPrisms } from "../funcs/prisms-list-prisms.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Prisms extends ClientSDK {
  /**
   * Catalog of preset prisms
   *
   * @remarks
   * Static catalog of one-click creative recipes. Filter by category or compatible media type.
   */
  async listPrisms(
    request?: operations.ListPrismsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPrismsResponse> {
    return unwrapAsync(prismsListPrisms(
      this,
      request,
      options,
    ));
  }

  /**
   * Apply a prism to an asset or new generation
   *
   * @remarks
   * Queues prism execution. Returns the queued Job; poll `/v1/jobs/{id}`
   * for terminal state. Provide exactly one of `asset_id`, `image_params`,
   * `video_params`.
   */
  async applyPrism(
    request: operations.ApplyPrismRequest,
    options?: RequestOptions,
  ): Promise<models.Job> {
    return unwrapAsync(prismsApplyPrism(
      this,
      request,
      options,
    ));
  }
}
