/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { APIKeys } from "./api-keys.js";
import { Characters } from "./characters.js";
import { Discovery } from "./discovery.js";
import { Generation } from "./generation.js";
import { Jobs } from "./jobs.js";
import { Prisms } from "./prisms.js";
import { Wallet } from "./wallet.js";

export class Aeriox extends ClientSDK {
  private _discovery?: Discovery;
  get discovery(): Discovery {
    return (this._discovery ??= new Discovery(this._options));
  }

  private _apiKeys?: APIKeys;
  get apiKeys(): APIKeys {
    return (this._apiKeys ??= new APIKeys(this._options));
  }

  private _wallet?: Wallet;
  get wallet(): Wallet {
    return (this._wallet ??= new Wallet(this._options));
  }

  private _generation?: Generation;
  get generation(): Generation {
    return (this._generation ??= new Generation(this._options));
  }

  private _jobs?: Jobs;
  get jobs(): Jobs {
    return (this._jobs ??= new Jobs(this._options));
  }

  private _characters?: Characters;
  get characters(): Characters {
    return (this._characters ??= new Characters(this._options));
  }

  private _prisms?: Prisms;
  get prisms(): Prisms {
    return (this._prisms ??= new Prisms(this._options));
  }
}
