/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { walletConfigureAutoRecharge } from "../funcs/wallet-configure-auto-recharge.js";
import { walletGetCredits } from "../funcs/wallet-get-credits.js";
import { walletGetWallet } from "../funcs/wallet-get-wallet.js";
import { walletTopUpWallet } from "../funcs/wallet-top-up-wallet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Wallet extends ClientSDK {
  /**
   * Get wallet balance and recent transactions
   */
  async getWallet(
    request?: operations.GetWalletRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetWalletResponse> {
    return unwrapAsync(walletGetWallet(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a Stripe PaymentIntent to credit the wallet
   *
   * @remarks
   * Creates a Stripe PaymentIntent against the workspace's saved customer.
   * If `payment_method_id` is provided, the intent is confirmed immediately
   * (off-session); otherwise the `client_secret` is returned for the client
   * to confirm via Stripe.js. Webhook credits the wallet on success.
   */
  async topUpWallet(
    request: operations.TopUpWalletRequest,
    options?: RequestOptions,
  ): Promise<operations.TopUpWalletResponse> {
    return unwrapAsync(walletTopUpWallet(
      this,
      request,
      options,
    ));
  }

  /**
   * Configure or clear wallet auto-recharge
   *
   * @remarks
   * Configures auto-recharge thresholds for the workspace. When `enabled`
   * is `false`, all auto-recharge fields are cleared. When `true`, the
   * threshold, top-up amount, and saved Stripe payment method are set.
   */
  async configureAutoRecharge(
    request: operations.ConfigureAutoRechargeRequest,
    options?: RequestOptions,
  ): Promise<operations.ConfigureAutoRechargeResponse> {
    return unwrapAsync(walletConfigureAutoRecharge(
      this,
      request,
      options,
    ));
  }

  /**
   * (Deprecated) Get legacy credit balance
   *
   * @remarks
   * Legacy endpoint exposing the universal credit pool plus 24h spend stats.
   * Deprecated — use `/v1/wallet` for USD wallet state.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async getCredits(
    options?: RequestOptions,
  ): Promise<operations.GetCreditsResponse> {
    return unwrapAsync(walletGetCredits(
      this,
      options,
    ));
  }
}
