/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @aeriox-co/api SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx discoveryGetOpenApiSpec.example.ts
 */

import { Aeriox } from "@aeriox-co/api";

const aeriox = new Aeriox();

async function main() {
  const result = await aeriox.discovery.getOpenApiSpec();

  console.log(result);
}

main().catch(console.error);
