/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ApplyPrismRequestBody = {
  assetId?: string | undefined;
  imageParams?: models.GenerateImageRequest | undefined;
  videoParams?: models.GenerateVideoRequest | undefined;
};

export type ApplyPrismRequest = {
  id: string;
  body: ApplyPrismRequestBody;
};

/** @internal */
export type ApplyPrismRequestBody$Outbound = {
  asset_id?: string | undefined;
  image_params?: models.GenerateImageRequest$Outbound | undefined;
  video_params?: models.GenerateVideoRequest$Outbound | undefined;
};

/** @internal */
export const ApplyPrismRequestBody$outboundSchema: z.ZodMiniType<
  ApplyPrismRequestBody$Outbound,
  ApplyPrismRequestBody
> = z.pipe(
  z.object({
    assetId: z.optional(z.string()),
    imageParams: z.optional(models.GenerateImageRequest$outboundSchema),
    videoParams: z.optional(models.GenerateVideoRequest$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      assetId: "asset_id",
      imageParams: "image_params",
      videoParams: "video_params",
    });
  }),
);

export function applyPrismRequestBodyToJSON(
  applyPrismRequestBody: ApplyPrismRequestBody,
): string {
  return JSON.stringify(
    ApplyPrismRequestBody$outboundSchema.parse(applyPrismRequestBody),
  );
}

/** @internal */
export type ApplyPrismRequest$Outbound = {
  id: string;
  body: ApplyPrismRequestBody$Outbound;
};

/** @internal */
export const ApplyPrismRequest$outboundSchema: z.ZodMiniType<
  ApplyPrismRequest$Outbound,
  ApplyPrismRequest
> = z.object({
  id: z.string(),
  body: z.lazy(() => ApplyPrismRequestBody$outboundSchema),
});

export function applyPrismRequestToJSON(
  applyPrismRequest: ApplyPrismRequest,
): string {
  return JSON.stringify(
    ApplyPrismRequest$outboundSchema.parse(applyPrismRequest),
  );
}
