/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CancelJobRequest = {
  id: string;
};

/** @internal */
export type CancelJobRequest$Outbound = {
  id: string;
};

/** @internal */
export const CancelJobRequest$outboundSchema: z.ZodMiniType<
  CancelJobRequest$Outbound,
  CancelJobRequest
> = z.object({
  id: z.string(),
});

export function cancelJobRequestToJSON(
  cancelJobRequest: CancelJobRequest,
): string {
  return JSON.stringify(
    CancelJobRequest$outboundSchema.parse(cancelJobRequest),
  );
}
