/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type RequestBody2 = {
  enabled: true;
  thresholdUsd: number;
  amountUsd: number;
  stripePaymentMethodId: string;
};

export type RequestBody1 = {
  enabled: false;
};

export type ConfigureAutoRechargeRequest = RequestBody2 | RequestBody1;

/**
 * Auto-recharge configuration applied
 */
export type ConfigureAutoRechargeResponse = {
  enabled: boolean;
  thresholdUsd?: number | undefined;
  amountUsd?: number | undefined;
};

/** @internal */
export type RequestBody2$Outbound = {
  enabled: true;
  threshold_usd: number;
  amount_usd: number;
  stripe_payment_method_id: string;
};

/** @internal */
export const RequestBody2$outboundSchema: z.ZodMiniType<
  RequestBody2$Outbound,
  RequestBody2
> = z.pipe(
  z.object({
    enabled: z.literal(true),
    thresholdUsd: z.number(),
    amountUsd: z.number(),
    stripePaymentMethodId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      thresholdUsd: "threshold_usd",
      amountUsd: "amount_usd",
      stripePaymentMethodId: "stripe_payment_method_id",
    });
  }),
);

export function requestBody2ToJSON(requestBody2: RequestBody2): string {
  return JSON.stringify(RequestBody2$outboundSchema.parse(requestBody2));
}

/** @internal */
export type RequestBody1$Outbound = {
  enabled: false;
};

/** @internal */
export const RequestBody1$outboundSchema: z.ZodMiniType<
  RequestBody1$Outbound,
  RequestBody1
> = z.object({
  enabled: z.literal(false),
});

export function requestBody1ToJSON(requestBody1: RequestBody1): string {
  return JSON.stringify(RequestBody1$outboundSchema.parse(requestBody1));
}

/** @internal */
export type ConfigureAutoRechargeRequest$Outbound =
  | RequestBody2$Outbound
  | RequestBody1$Outbound;

/** @internal */
export const ConfigureAutoRechargeRequest$outboundSchema: z.ZodMiniType<
  ConfigureAutoRechargeRequest$Outbound,
  ConfigureAutoRechargeRequest
> = smartUnion([
  z.lazy(() => RequestBody2$outboundSchema),
  z.lazy(() => RequestBody1$outboundSchema),
]);

export function configureAutoRechargeRequestToJSON(
  configureAutoRechargeRequest: ConfigureAutoRechargeRequest,
): string {
  return JSON.stringify(
    ConfigureAutoRechargeRequest$outboundSchema.parse(
      configureAutoRechargeRequest,
    ),
  );
}

/** @internal */
export const ConfigureAutoRechargeResponse$inboundSchema: z.ZodMiniType<
  ConfigureAutoRechargeResponse,
  unknown
> = z.pipe(
  z.object({
    enabled: types.boolean(),
    threshold_usd: types.optional(types.number()),
    amount_usd: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "threshold_usd": "thresholdUsd",
      "amount_usd": "amountUsd",
    });
  }),
);

export function configureAutoRechargeResponseFromJSON(
  jsonString: string,
): SafeParseResult<ConfigureAutoRechargeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConfigureAutoRechargeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConfigureAutoRechargeResponse' from JSON`,
  );
}
