/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Lora = {
  path: string;
  scale: number;
};

export type CreateGenerationRequest = {
  model: string;
  prompt: string;
  negativePrompt?: string | undefined;
  aspectRatio?: string | undefined;
  resolution?: string | undefined;
  duration?: number | undefined;
  withAudio?: boolean | undefined;
  seedImageUrl?: string | undefined;
  loras?: Array<Lora> | undefined;
};

export const CreateGenerationStatus = {
  Queued: "queued",
} as const;
export type CreateGenerationStatus = ClosedEnum<typeof CreateGenerationStatus>;

export const CreateGenerationKind = {
  Image: "image",
  Video: "video",
} as const;
export type CreateGenerationKind = OpenEnum<typeof CreateGenerationKind>;

export type Cost = {
  usdMicros?: number | undefined;
  usd?: number | undefined;
};

/**
 * Generation queued
 */
export type CreateGenerationResponseBody = {
  generationId: string | null;
  providerRequestId?: string | null | undefined;
  status: CreateGenerationStatus;
  model: string;
  kind?: CreateGenerationKind | undefined;
  /**
   * Studio credit units charged (legacy display field; not USD; informational only for API-key callers).
   */
  creditsCharged?: number | undefined;
  cost?: Cost | undefined;
  pollUrl?: string | null | undefined;
};

export type CreateGenerationResponse = {
  headers: { [k: string]: Array<string> };
  result: CreateGenerationResponseBody;
};

/** @internal */
export type Lora$Outbound = {
  path: string;
  scale: number;
};

/** @internal */
export const Lora$outboundSchema: z.ZodMiniType<Lora$Outbound, Lora> = z.object(
  {
    path: z.string(),
    scale: z.number(),
  },
);

export function loraToJSON(lora: Lora): string {
  return JSON.stringify(Lora$outboundSchema.parse(lora));
}

/** @internal */
export type CreateGenerationRequest$Outbound = {
  model: string;
  prompt: string;
  negative_prompt?: string | undefined;
  aspect_ratio?: string | undefined;
  resolution?: string | undefined;
  duration?: number | undefined;
  with_audio?: boolean | undefined;
  seed_image_url?: string | undefined;
  loras?: Array<Lora$Outbound> | undefined;
};

/** @internal */
export const CreateGenerationRequest$outboundSchema: z.ZodMiniType<
  CreateGenerationRequest$Outbound,
  CreateGenerationRequest
> = z.pipe(
  z.object({
    model: z.string(),
    prompt: z.string(),
    negativePrompt: z.optional(z.string()),
    aspectRatio: z.optional(z.string()),
    resolution: z.optional(z.string()),
    duration: z.optional(z.int()),
    withAudio: z.optional(z.boolean()),
    seedImageUrl: z.optional(z.string()),
    loras: z.optional(z.array(z.lazy(() => Lora$outboundSchema))),
  }),
  z.transform((v) => {
    return remap$(v, {
      negativePrompt: "negative_prompt",
      aspectRatio: "aspect_ratio",
      withAudio: "with_audio",
      seedImageUrl: "seed_image_url",
    });
  }),
);

export function createGenerationRequestToJSON(
  createGenerationRequest: CreateGenerationRequest,
): string {
  return JSON.stringify(
    CreateGenerationRequest$outboundSchema.parse(createGenerationRequest),
  );
}

/** @internal */
export const CreateGenerationStatus$inboundSchema: z.ZodMiniEnum<
  typeof CreateGenerationStatus
> = z.enum(CreateGenerationStatus);

/** @internal */
export const CreateGenerationKind$inboundSchema: z.ZodMiniType<
  CreateGenerationKind,
  unknown
> = openEnums.inboundSchema(CreateGenerationKind);

/** @internal */
export const Cost$inboundSchema: z.ZodMiniType<Cost, unknown> = z.pipe(
  z.object({
    usd_micros: types.optional(types.number()),
    usd: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "usd_micros": "usdMicros",
    });
  }),
);

export function costFromJSON(
  jsonString: string,
): SafeParseResult<Cost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Cost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Cost' from JSON`,
  );
}

/** @internal */
export const CreateGenerationResponseBody$inboundSchema: z.ZodMiniType<
  CreateGenerationResponseBody,
  unknown
> = z.pipe(
  z.object({
    generation_id: types.nullable(types.string()),
    provider_request_id: z.optional(z.nullable(types.string())),
    status: CreateGenerationStatus$inboundSchema,
    model: types.string(),
    kind: types.optional(CreateGenerationKind$inboundSchema),
    credits_charged: types.optional(types.number()),
    cost: types.optional(z.lazy(() => Cost$inboundSchema)),
    poll_url: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "generation_id": "generationId",
      "provider_request_id": "providerRequestId",
      "credits_charged": "creditsCharged",
      "poll_url": "pollUrl",
    });
  }),
);

export function createGenerationResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateGenerationResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateGenerationResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGenerationResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateGenerationResponse$inboundSchema: z.ZodMiniType<
  CreateGenerationResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => CreateGenerationResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function createGenerationResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateGenerationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateGenerationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGenerationResponse' from JSON`,
  );
}
