/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type CreateCharacterRequest = {
  name: string;
  imageUrls: Array<string>;
  attributes?: { [k: string]: any } | undefined;
};

export const Type = {
  Image: "image",
  Video: "video",
  Audio: "audio",
  Compose: "compose",
  CharacterTrain: "character_train",
  PrismApply: "prism_apply",
} as const;
export type Type = OpenEnum<typeof Type>;

export const CreateCharacterStatus = {
  Queued: "queued",
  Running: "running",
  Completed: "completed",
  Failed: "failed",
  Cancelled: "cancelled",
  NsfwBlocked: "nsfw_blocked",
} as const;
export type CreateCharacterStatus = OpenEnum<typeof CreateCharacterStatus>;

export type ErrorError = {
  code: string;
  message?: string | undefined;
  details?: { [k: string]: any } | undefined;
};

export type ErrorT = {
  error: ErrorError;
};

/**
 * Training queued
 */
export type CreateCharacterResponse = {
  jobId: string;
  type: Type;
  status: CreateCharacterStatus;
  progressPct?: number | null | undefined;
  estimatedCostUsd?: number | null | undefined;
  chargedCostUsd?: number | null | undefined;
  outputUrls?: Array<string> | null | undefined;
  error?: ErrorT | null | undefined;
  createdAt: Date;
  completedAt?: Date | null | undefined;
  /**
   * Present only when `type=prism_apply`. Identifies the prism that was applied.
   */
  prismId?: string | undefined;
  characterId?: string | undefined;
};

/** @internal */
export type CreateCharacterRequest$Outbound = {
  name: string;
  image_urls: Array<string>;
  attributes?: { [k: string]: any } | undefined;
};

/** @internal */
export const CreateCharacterRequest$outboundSchema: z.ZodMiniType<
  CreateCharacterRequest$Outbound,
  CreateCharacterRequest
> = z.pipe(
  z.object({
    name: z.string(),
    imageUrls: z.array(z.string()),
    attributes: z.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      imageUrls: "image_urls",
    });
  }),
);

export function createCharacterRequestToJSON(
  createCharacterRequest: CreateCharacterRequest,
): string {
  return JSON.stringify(
    CreateCharacterRequest$outboundSchema.parse(createCharacterRequest),
  );
}

/** @internal */
export const Type$inboundSchema: z.ZodMiniType<Type, unknown> = openEnums
  .inboundSchema(Type);

/** @internal */
export const CreateCharacterStatus$inboundSchema: z.ZodMiniType<
  CreateCharacterStatus,
  unknown
> = openEnums.inboundSchema(CreateCharacterStatus);

/** @internal */
export const ErrorError$inboundSchema: z.ZodMiniType<ErrorError, unknown> = z
  .object({
    code: types.string(),
    message: types.optional(types.string()),
    details: types.optional(z.record(z.string(), z.any())),
  });

export function errorErrorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorError' from JSON`,
  );
}

/** @internal */
export const ErrorT$inboundSchema: z.ZodMiniType<ErrorT, unknown> = z.object({
  error: z.lazy(() => ErrorError$inboundSchema),
});

export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}

/** @internal */
export const CreateCharacterResponse$inboundSchema: z.ZodMiniType<
  CreateCharacterResponse,
  unknown
> = z.pipe(
  z.object({
    job_id: types.string(),
    type: Type$inboundSchema,
    status: CreateCharacterStatus$inboundSchema,
    progress_pct: z.optional(z.nullable(types.number())),
    estimated_cost_usd: z.optional(z.nullable(types.number())),
    charged_cost_usd: z.optional(z.nullable(types.number())),
    output_urls: z.optional(z.nullable(z.array(types.string()))),
    error: z.optional(z.nullable(z.lazy(() => ErrorT$inboundSchema))),
    created_at: types.date(),
    completed_at: z.optional(z.nullable(types.date())),
    prism_id: types.optional(types.string()),
    character_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "job_id": "jobId",
      "progress_pct": "progressPct",
      "estimated_cost_usd": "estimatedCostUsd",
      "charged_cost_usd": "chargedCostUsd",
      "output_urls": "outputUrls",
      "created_at": "createdAt",
      "completed_at": "completedAt",
      "prism_id": "prismId",
      "character_id": "characterId",
    });
  }),
);

export function createCharacterResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateCharacterResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateCharacterResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateCharacterResponse' from JSON`,
  );
}
