/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Edge = {
  toCardId?: string | undefined;
  toNodeId?: string | undefined;
  edgeType: string;
  attributes?: { [k: string]: any } | undefined;
};

export type CreateNodeRequest = {
  cardType?: string | undefined;
  nodeType?: string | undefined;
  name: string;
  description?: string | undefined;
  attributes?: { [k: string]: any } | undefined;
  previewUrl?: string | undefined;
  thumbUrl?: string | undefined;
  parentId?: string | null | undefined;
  visibilityScopes?: Array<string> | undefined;
  edges?: Array<Edge> | undefined;
};

/**
 * Card created
 */
export type CreateNodeResponse = {
  node: { [k: string]: any };
  card: { [k: string]: any };
};

/** @internal */
export type Edge$Outbound = {
  to_card_id?: string | undefined;
  to_node_id?: string | undefined;
  edge_type: string;
  attributes?: { [k: string]: any } | undefined;
};

/** @internal */
export const Edge$outboundSchema: z.ZodMiniType<Edge$Outbound, Edge> = z.pipe(
  z.object({
    toCardId: z.optional(z.string()),
    toNodeId: z.optional(z.string()),
    edgeType: z.string(),
    attributes: z.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      toCardId: "to_card_id",
      toNodeId: "to_node_id",
      edgeType: "edge_type",
    });
  }),
);

export function edgeToJSON(edge: Edge): string {
  return JSON.stringify(Edge$outboundSchema.parse(edge));
}

/** @internal */
export type CreateNodeRequest$Outbound = {
  card_type?: string | undefined;
  node_type?: string | undefined;
  name: string;
  description?: string | undefined;
  attributes?: { [k: string]: any } | undefined;
  preview_url?: string | undefined;
  thumb_url?: string | undefined;
  parent_id?: string | null | undefined;
  visibility_scopes?: Array<string> | undefined;
  edges?: Array<Edge$Outbound> | undefined;
};

/** @internal */
export const CreateNodeRequest$outboundSchema: z.ZodMiniType<
  CreateNodeRequest$Outbound,
  CreateNodeRequest
> = z.pipe(
  z.object({
    cardType: z.optional(z.string()),
    nodeType: z.optional(z.string()),
    name: z.string(),
    description: z.optional(z.string()),
    attributes: z.optional(z.record(z.string(), z.any())),
    previewUrl: z.optional(z.string()),
    thumbUrl: z.optional(z.string()),
    parentId: z.optional(z.nullable(z.string())),
    visibilityScopes: z.optional(z.array(z.string())),
    edges: z.optional(z.array(z.lazy(() => Edge$outboundSchema))),
  }),
  z.transform((v) => {
    return remap$(v, {
      cardType: "card_type",
      nodeType: "node_type",
      previewUrl: "preview_url",
      thumbUrl: "thumb_url",
      parentId: "parent_id",
      visibilityScopes: "visibility_scopes",
    });
  }),
);

export function createNodeRequestToJSON(
  createNodeRequest: CreateNodeRequest,
): string {
  return JSON.stringify(
    CreateNodeRequest$outboundSchema.parse(createNodeRequest),
  );
}

/** @internal */
export const CreateNodeResponse$inboundSchema: z.ZodMiniType<
  CreateNodeResponse,
  unknown
> = z.object({
  node: z.record(z.string(), z.any()),
  card: z.record(z.string(), z.any()),
});

export function createNodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateNodeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateNodeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateNodeResponse' from JSON`,
  );
}
