/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteNodeRequest = {
  id: string;
};

/**
 * Deleted
 */
export type DeleteNodeResponse = {
  ok: boolean;
  softDeleted: boolean;
};

/** @internal */
export type DeleteNodeRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteNodeRequest$outboundSchema: z.ZodMiniType<
  DeleteNodeRequest$Outbound,
  DeleteNodeRequest
> = z.object({
  id: z.string(),
});

export function deleteNodeRequestToJSON(
  deleteNodeRequest: DeleteNodeRequest,
): string {
  return JSON.stringify(
    DeleteNodeRequest$outboundSchema.parse(deleteNodeRequest),
  );
}

/** @internal */
export const DeleteNodeResponse$inboundSchema: z.ZodMiniType<
  DeleteNodeResponse,
  unknown
> = z.pipe(
  z.object({
    ok: types.boolean(),
    soft_deleted: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "soft_deleted": "softDeleted",
    });
  }),
);

export function deleteNodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteNodeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteNodeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteNodeResponse' from JSON`,
  );
}
