/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteCharacterRequest = {
  id: string;
};

/** @internal */
export type DeleteCharacterRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteCharacterRequest$outboundSchema: z.ZodMiniType<
  DeleteCharacterRequest$Outbound,
  DeleteCharacterRequest
> = z.object({
  id: z.string(),
});

export function deleteCharacterRequestToJSON(
  deleteCharacterRequest: DeleteCharacterRequest,
): string {
  return JSON.stringify(
    DeleteCharacterRequest$outboundSchema.parse(deleteCharacterRequest),
  );
}
