/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type EstimateGenerationRequest = {
  model: string;
  prompt: string;
  duration?: number | undefined;
};

export const EstimateGenerationKind = {
  Image: "image",
  Video: "video",
} as const;
export type EstimateGenerationKind = OpenEnum<typeof EstimateGenerationKind>;

export const ReasonsBlocked = {
  UnknownModel: "unknown_model",
  InsufficientCredits: "insufficient_credits",
  CircuitOpen: "circuit_open",
  PromptBlocked: "prompt_blocked",
  SpendCapExceeded: "spend_cap_exceeded",
} as const;
export type ReasonsBlocked = OpenEnum<typeof ReasonsBlocked>;

/**
 * Estimate result
 */
export type EstimateGenerationResponse = {
  credits: number;
  usd: number;
  estimatedSeconds: number;
  model: string;
  kind?: EstimateGenerationKind | undefined;
  wouldSucceed: boolean;
  reasonsBlocked: Array<ReasonsBlocked>;
  currentBalance?: number | undefined;
  spendCap?: { [k: string]: any } | null | undefined;
};

/** @internal */
export type EstimateGenerationRequest$Outbound = {
  model: string;
  prompt: string;
  duration?: number | undefined;
};

/** @internal */
export const EstimateGenerationRequest$outboundSchema: z.ZodMiniType<
  EstimateGenerationRequest$Outbound,
  EstimateGenerationRequest
> = z.object({
  model: z.string(),
  prompt: z.string(),
  duration: z.optional(z.int()),
});

export function estimateGenerationRequestToJSON(
  estimateGenerationRequest: EstimateGenerationRequest,
): string {
  return JSON.stringify(
    EstimateGenerationRequest$outboundSchema.parse(estimateGenerationRequest),
  );
}

/** @internal */
export const EstimateGenerationKind$inboundSchema: z.ZodMiniType<
  EstimateGenerationKind,
  unknown
> = openEnums.inboundSchema(EstimateGenerationKind);

/** @internal */
export const ReasonsBlocked$inboundSchema: z.ZodMiniType<
  ReasonsBlocked,
  unknown
> = openEnums.inboundSchema(ReasonsBlocked);

/** @internal */
export const EstimateGenerationResponse$inboundSchema: z.ZodMiniType<
  EstimateGenerationResponse,
  unknown
> = z.pipe(
  z.object({
    credits: types.number(),
    usd: types.number(),
    estimated_seconds: types.number(),
    model: types.string(),
    kind: types.optional(EstimateGenerationKind$inboundSchema),
    would_succeed: types.boolean(),
    reasons_blocked: z.array(ReasonsBlocked$inboundSchema),
    current_balance: types.optional(types.number()),
    spend_cap: z.optional(z.nullable(z.record(z.string(), z.any()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "estimated_seconds": "estimatedSeconds",
      "would_succeed": "wouldSucceed",
      "reasons_blocked": "reasonsBlocked",
      "current_balance": "currentBalance",
      "spend_cap": "spendCap",
    });
  }),
);

export function estimateGenerationResponseFromJSON(
  jsonString: string,
): SafeParseResult<EstimateGenerationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EstimateGenerationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EstimateGenerationResponse' from JSON`,
  );
}
