/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetWalletRequest = {
  limit?: number | undefined;
};

/**
 * Wallet snapshot
 */
export type GetWalletResponse = {
  balance: { [k: string]: any };
  recentTransactions: Array<{ [k: string]: any }>;
};

/** @internal */
export type GetWalletRequest$Outbound = {
  limit: number;
};

/** @internal */
export const GetWalletRequest$outboundSchema: z.ZodMiniType<
  GetWalletRequest$Outbound,
  GetWalletRequest
> = z.object({
  limit: z._default(z.int(), 20),
});

export function getWalletRequestToJSON(
  getWalletRequest: GetWalletRequest,
): string {
  return JSON.stringify(
    GetWalletRequest$outboundSchema.parse(getWalletRequest),
  );
}

/** @internal */
export const GetWalletResponse$inboundSchema: z.ZodMiniType<
  GetWalletResponse,
  unknown
> = z.pipe(
  z.object({
    balance: z.record(z.string(), z.any()),
    recent_transactions: z.array(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "recent_transactions": "recentTransactions",
    });
  }),
);

export function getWalletResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetWalletResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWalletResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWalletResponse' from JSON`,
  );
}
