/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Credits = {
  balance?: number | undefined;
  monthlyGrant?: number | undefined;
  purchased?: number | undefined;
};

/**
 * Credit balance
 */
export type GetCreditsResponse = {
  plan: string;
  credits: Credits;
  image?: { [k: string]: any } | undefined;
  video?: { [k: string]: any } | undefined;
  apiKey24hSpendUsd?: number | undefined;
  apiKeyDailyCapUsd?: number | null | undefined;
};

/** @internal */
export const Credits$inboundSchema: z.ZodMiniType<Credits, unknown> = z.pipe(
  z.object({
    balance: types.optional(types.number()),
    monthly_grant: types.optional(types.number()),
    purchased: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "monthly_grant": "monthlyGrant",
    });
  }),
);

export function creditsFromJSON(
  jsonString: string,
): SafeParseResult<Credits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Credits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Credits' from JSON`,
  );
}

/** @internal */
export const GetCreditsResponse$inboundSchema: z.ZodMiniType<
  GetCreditsResponse,
  unknown
> = z.pipe(
  z.object({
    plan: types.string(),
    credits: z.lazy(() => Credits$inboundSchema),
    image: types.optional(z.record(z.string(), z.any())),
    video: types.optional(z.record(z.string(), z.any())),
    api_key_24h_spend_usd: types.optional(types.number()),
    api_key_daily_cap_usd: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "api_key_24h_spend_usd": "apiKey24hSpendUsd",
      "api_key_daily_cap_usd": "apiKeyDailyCapUsd",
    });
  }),
);

export function getCreditsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCreditsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreditsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreditsResponse' from JSON`,
  );
}
