/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetNodeRequest = {
  id: string;
};

/**
 * Node + edges
 */
export type GetNodeResponse = {
  node: { [k: string]: any };
  edges: Array<{ [k: string]: any }>;
};

/** @internal */
export type GetNodeRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetNodeRequest$outboundSchema: z.ZodMiniType<
  GetNodeRequest$Outbound,
  GetNodeRequest
> = z.object({
  id: z.string(),
});

export function getNodeRequestToJSON(getNodeRequest: GetNodeRequest): string {
  return JSON.stringify(GetNodeRequest$outboundSchema.parse(getNodeRequest));
}

/** @internal */
export const GetNodeResponse$inboundSchema: z.ZodMiniType<
  GetNodeResponse,
  unknown
> = z.object({
  node: z.record(z.string(), z.any()),
  edges: z.array(z.record(z.string(), z.any())),
});

export function getNodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetNodeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetNodeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetNodeResponse' from JSON`,
  );
}
