/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetCharacterRequest = {
  id: string;
};

/** @internal */
export type GetCharacterRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCharacterRequest$outboundSchema: z.ZodMiniType<
  GetCharacterRequest$Outbound,
  GetCharacterRequest
> = z.object({
  id: z.string(),
});

export function getCharacterRequestToJSON(
  getCharacterRequest: GetCharacterRequest,
): string {
  return JSON.stringify(
    GetCharacterRequest$outboundSchema.parse(getCharacterRequest),
  );
}
