/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Workspace = {
  id?: string | undefined;
  name?: string | undefined;
  plan?: string | undefined;
  createdAt?: Date | undefined;
};

export type ApiKey = {
  prefix?: string | undefined;
  scopes?: Array<string> | undefined;
  dailySpendCapUsd?: number | null | undefined;
};

/**
 * Workspace + API key info
 */
export type GetMeResponse = {
  workspace: Workspace;
  apiKey: ApiKey;
};

/** @internal */
export const Workspace$inboundSchema: z.ZodMiniType<Workspace, unknown> = z
  .pipe(
    z.object({
      id: types.optional(types.string()),
      name: types.optional(types.string()),
      plan: types.optional(types.string()),
      created_at: types.optional(types.date()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "created_at": "createdAt",
      });
    }),
  );

export function workspaceFromJSON(
  jsonString: string,
): SafeParseResult<Workspace, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Workspace$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Workspace' from JSON`,
  );
}

/** @internal */
export const ApiKey$inboundSchema: z.ZodMiniType<ApiKey, unknown> = z.pipe(
  z.object({
    prefix: types.optional(types.string()),
    scopes: types.optional(z.array(types.string())),
    daily_spend_cap_usd: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "daily_spend_cap_usd": "dailySpendCapUsd",
    });
  }),
);

export function apiKeyFromJSON(
  jsonString: string,
): SafeParseResult<ApiKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiKey' from JSON`,
  );
}

/** @internal */
export const GetMeResponse$inboundSchema: z.ZodMiniType<
  GetMeResponse,
  unknown
> = z.pipe(
  z.object({
    workspace: z.lazy(() => Workspace$inboundSchema),
    api_key: z.lazy(() => ApiKey$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "api_key": "apiKey",
    });
  }),
);

export function getMeResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetMeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMeResponse' from JSON`,
  );
}
