/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetGenerationRequest = {
  id: string;
};

export const GetGenerationStatus = {
  Queued: "queued",
  Running: "running",
  Success: "success",
  Failed: "failed",
} as const;
export type GetGenerationStatus = OpenEnum<typeof GetGenerationStatus>;

/**
 * Generation row
 */
export type GetGenerationResponse = {
  id: string;
  status: GetGenerationStatus;
  model: string;
  prompt?: string | undefined;
  kind?: string | null | undefined;
  /**
   * Studio credit units charged (legacy display field; not USD; informational only for API-key callers).
   */
  creditsCharged?: number | null | undefined;
  assetUrls?: Array<string> | undefined;
  error?: string | null | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | null | undefined;
};

/** @internal */
export type GetGenerationRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetGenerationRequest$outboundSchema: z.ZodMiniType<
  GetGenerationRequest$Outbound,
  GetGenerationRequest
> = z.object({
  id: z.string(),
});

export function getGenerationRequestToJSON(
  getGenerationRequest: GetGenerationRequest,
): string {
  return JSON.stringify(
    GetGenerationRequest$outboundSchema.parse(getGenerationRequest),
  );
}

/** @internal */
export const GetGenerationStatus$inboundSchema: z.ZodMiniType<
  GetGenerationStatus,
  unknown
> = openEnums.inboundSchema(GetGenerationStatus);

/** @internal */
export const GetGenerationResponse$inboundSchema: z.ZodMiniType<
  GetGenerationResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    status: GetGenerationStatus$inboundSchema,
    model: types.string(),
    prompt: types.optional(types.string()),
    kind: z.optional(z.nullable(types.string())),
    credits_charged: z.optional(z.nullable(types.number())),
    asset_urls: types.optional(z.array(types.string())),
    error: z.optional(z.nullable(types.string())),
    created_at: types.optional(types.date()),
    updated_at: z.optional(z.nullable(types.date())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "credits_charged": "creditsCharged",
      "asset_urls": "assetUrls",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function getGenerationResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetGenerationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGenerationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGenerationResponse' from JSON`,
  );
}
