/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Operation = {
  operationId: string;
  model: string;
  provider: string;
  unit: string;
  priceUsdMicros: number;
  priceUsd: number;
  notes?: string | null | undefined;
};

/**
 * Rate card
 */
export type GetPricingResponse = {
  currency: string;
  microsPerUnit: number;
  operations: Array<Operation>;
  generatedAt: Date;
};

/** @internal */
export const Operation$inboundSchema: z.ZodMiniType<Operation, unknown> = z
  .pipe(
    z.object({
      operation_id: types.string(),
      model: types.string(),
      provider: types.string(),
      unit: types.string(),
      price_usd_micros: types.number(),
      price_usd: types.number(),
      notes: z.optional(z.nullable(types.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "operation_id": "operationId",
        "price_usd_micros": "priceUsdMicros",
        "price_usd": "priceUsd",
      });
    }),
  );

export function operationFromJSON(
  jsonString: string,
): SafeParseResult<Operation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Operation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Operation' from JSON`,
  );
}

/** @internal */
export const GetPricingResponse$inboundSchema: z.ZodMiniType<
  GetPricingResponse,
  unknown
> = z.pipe(
  z.object({
    currency: types.string(),
    micros_per_unit: types.number(),
    operations: z.array(z.lazy(() => Operation$inboundSchema)),
    generated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "micros_per_unit": "microsPerUnit",
      "generated_at": "generatedAt",
    });
  }),
);

export function getPricingResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPricingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPricingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPricingResponse' from JSON`,
  );
}
