/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetJobRequest = {
  id: string;
};

/** @internal */
export type GetJobRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetJobRequest$outboundSchema: z.ZodMiniType<
  GetJobRequest$Outbound,
  GetJobRequest
> = z.object({
  id: z.string(),
});

export function getJobRequestToJSON(getJobRequest: GetJobRequest): string {
  return JSON.stringify(GetJobRequest$outboundSchema.parse(getJobRequest));
}
