/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const GlobalsOnly = {
  One: "1",
} as const;
export type GlobalsOnly = ClosedEnum<typeof GlobalsOnly>;

export type ListNodesRequest = {
  type?: string | undefined;
  scope?: string | undefined;
  globalsOnly?: GlobalsOnly | undefined;
  parentId?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/**
 * Card list (dual-emitted)
 */
export type ListNodesResponse = {
  nodes: Array<{ [k: string]: any }>;
  cards: Array<{ [k: string]: any }>;
  count: number;
  limit: number;
  offset: number;
};

/** @internal */
export const GlobalsOnly$outboundSchema: z.ZodMiniEnum<typeof GlobalsOnly> = z
  .enum(GlobalsOnly);

/** @internal */
export type ListNodesRequest$Outbound = {
  type?: string | undefined;
  scope?: string | undefined;
  globals_only?: string | undefined;
  parent_id?: string | undefined;
  limit: number;
  offset: number;
};

/** @internal */
export const ListNodesRequest$outboundSchema: z.ZodMiniType<
  ListNodesRequest$Outbound,
  ListNodesRequest
> = z.pipe(
  z.object({
    type: z.optional(z.string()),
    scope: z.optional(z.string()),
    globalsOnly: z.optional(GlobalsOnly$outboundSchema),
    parentId: z.optional(z.string()),
    limit: z._default(z.int(), 50),
    offset: z._default(z.int(), 0),
  }),
  z.transform((v) => {
    return remap$(v, {
      globalsOnly: "globals_only",
      parentId: "parent_id",
    });
  }),
);

export function listNodesRequestToJSON(
  listNodesRequest: ListNodesRequest,
): string {
  return JSON.stringify(
    ListNodesRequest$outboundSchema.parse(listNodesRequest),
  );
}

/** @internal */
export const ListNodesResponse$inboundSchema: z.ZodMiniType<
  ListNodesResponse,
  unknown
> = z.object({
  nodes: z.array(z.record(z.string(), z.any())),
  cards: z.array(z.record(z.string(), z.any())),
  count: types.number(),
  limit: types.number(),
  offset: types.number(),
});

export function listNodesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListNodesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListNodesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListNodesResponse' from JSON`,
  );
}
