/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListCharactersRequest = {
  limit?: number | undefined;
  cursor?: string | undefined;
};

/**
 * List of characters
 */
export type ListCharactersResponse = {
  data: Array<models.Character>;
  nextCursor?: string | null | undefined;
};

/** @internal */
export type ListCharactersRequest$Outbound = {
  limit: number;
  cursor?: string | undefined;
};

/** @internal */
export const ListCharactersRequest$outboundSchema: z.ZodMiniType<
  ListCharactersRequest$Outbound,
  ListCharactersRequest
> = z.object({
  limit: z._default(z.int(), 20),
  cursor: z.optional(z.string()),
});

export function listCharactersRequestToJSON(
  listCharactersRequest: ListCharactersRequest,
): string {
  return JSON.stringify(
    ListCharactersRequest$outboundSchema.parse(listCharactersRequest),
  );
}

/** @internal */
export const ListCharactersResponse$inboundSchema: z.ZodMiniType<
  ListCharactersResponse,
  unknown
> = z.pipe(
  z.object({
    data: z.array(models.Character$inboundSchema),
    next_cursor: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function listCharactersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCharactersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCharactersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCharactersResponse' from JSON`,
  );
}
