/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const CompatibleWith = {
  Image: "image",
  Video: "video",
  Audio: "audio",
} as const;
export type CompatibleWith = ClosedEnum<typeof CompatibleWith>;

export type ListPrismsRequest = {
  category?: string | undefined;
  compatibleWith?: CompatibleWith | undefined;
};

/**
 * Prism catalog
 */
export type ListPrismsResponse = {
  data: Array<models.Prism>;
};

/** @internal */
export const CompatibleWith$outboundSchema: z.ZodMiniEnum<
  typeof CompatibleWith
> = z.enum(CompatibleWith);

/** @internal */
export type ListPrismsRequest$Outbound = {
  category?: string | undefined;
  compatible_with?: string | undefined;
};

/** @internal */
export const ListPrismsRequest$outboundSchema: z.ZodMiniType<
  ListPrismsRequest$Outbound,
  ListPrismsRequest
> = z.pipe(
  z.object({
    category: z.optional(z.string()),
    compatibleWith: z.optional(CompatibleWith$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      compatibleWith: "compatible_with",
    });
  }),
);

export function listPrismsRequestToJSON(
  listPrismsRequest: ListPrismsRequest,
): string {
  return JSON.stringify(
    ListPrismsRequest$outboundSchema.parse(listPrismsRequest),
  );
}

/** @internal */
export const ListPrismsResponse$inboundSchema: z.ZodMiniType<
  ListPrismsResponse,
  unknown
> = z.object({
  data: z.array(models.Prism$inboundSchema),
});

export function listPrismsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPrismsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPrismsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPrismsResponse' from JSON`,
  );
}
