/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const ResponseType = {
  Code: "code",
} as const;
export type ResponseType = ClosedEnum<typeof ResponseType>;

export const CodeChallengeMethod = {
  S256: "S256",
} as const;
export type CodeChallengeMethod = ClosedEnum<typeof CodeChallengeMethod>;

export type OauthAuthorizeRequest = {
  responseType: ResponseType;
  clientId: string;
  redirectUri: string;
  codeChallenge: string;
  codeChallengeMethod: CodeChallengeMethod;
  scope?: string | undefined;
  state?: string | undefined;
};

/** @internal */
export const ResponseType$outboundSchema: z.ZodMiniEnum<typeof ResponseType> = z
  .enum(ResponseType);

/** @internal */
export const CodeChallengeMethod$outboundSchema: z.ZodMiniEnum<
  typeof CodeChallengeMethod
> = z.enum(CodeChallengeMethod);

/** @internal */
export type OauthAuthorizeRequest$Outbound = {
  response_type: string;
  client_id: string;
  redirect_uri: string;
  code_challenge: string;
  code_challenge_method: string;
  scope?: string | undefined;
  state?: string | undefined;
};

/** @internal */
export const OauthAuthorizeRequest$outboundSchema: z.ZodMiniType<
  OauthAuthorizeRequest$Outbound,
  OauthAuthorizeRequest
> = z.pipe(
  z.object({
    responseType: ResponseType$outboundSchema,
    clientId: z.string(),
    redirectUri: z.string(),
    codeChallenge: z.string(),
    codeChallengeMethod: CodeChallengeMethod$outboundSchema,
    scope: z.optional(z.string()),
    state: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      responseType: "response_type",
      clientId: "client_id",
      redirectUri: "redirect_uri",
      codeChallenge: "code_challenge",
      codeChallengeMethod: "code_challenge_method",
    });
  }),
);

export function oauthAuthorizeRequestToJSON(
  oauthAuthorizeRequest: OauthAuthorizeRequest,
): string {
  return JSON.stringify(
    OauthAuthorizeRequest$outboundSchema.parse(oauthAuthorizeRequest),
  );
}
