/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const TokenTypeHint = {
  AccessToken: "access_token",
  RefreshToken: "refresh_token",
} as const;
export type TokenTypeHint = ClosedEnum<typeof TokenTypeHint>;

export type OauthRevokeRequest = {
  token: string;
  tokenTypeHint?: TokenTypeHint | undefined;
  clientId?: string | undefined;
};

/** @internal */
export const TokenTypeHint$outboundSchema: z.ZodMiniEnum<typeof TokenTypeHint> =
  z.enum(TokenTypeHint);

/** @internal */
export type OauthRevokeRequest$Outbound = {
  token: string;
  token_type_hint?: string | undefined;
  client_id?: string | undefined;
};

/** @internal */
export const OauthRevokeRequest$outboundSchema: z.ZodMiniType<
  OauthRevokeRequest$Outbound,
  OauthRevokeRequest
> = z.pipe(
  z.object({
    token: z.string(),
    tokenTypeHint: z.optional(TokenTypeHint$outboundSchema),
    clientId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      tokenTypeHint: "token_type_hint",
      clientId: "client_id",
    });
  }),
);

export function oauthRevokeRequestToJSON(
  oauthRevokeRequest: OauthRevokeRequest,
): string {
  return JSON.stringify(
    OauthRevokeRequest$outboundSchema.parse(oauthRevokeRequest),
  );
}
