/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const GrantType = {
  AuthorizationCode: "authorization_code",
  RefreshToken: "refresh_token",
} as const;
export type GrantType = ClosedEnum<typeof GrantType>;

export type OauthTokenRequest = {
  grantType: GrantType;
  code?: string | undefined;
  redirectUri?: string | undefined;
  codeVerifier?: string | undefined;
  refreshToken?: string | undefined;
  clientId: string;
};

export const TokenType = {
  Bearer: "Bearer",
} as const;
export type TokenType = ClosedEnum<typeof TokenType>;

/**
 * Token response
 */
export type OauthTokenResponse = {
  accessToken: string;
  tokenType: TokenType;
  expiresIn: number;
  refreshToken?: string | null | undefined;
  scope?: string | undefined;
};

/** @internal */
export const GrantType$outboundSchema: z.ZodMiniEnum<typeof GrantType> = z.enum(
  GrantType,
);

/** @internal */
export type OauthTokenRequest$Outbound = {
  grant_type: string;
  code?: string | undefined;
  redirect_uri?: string | undefined;
  code_verifier?: string | undefined;
  refresh_token?: string | undefined;
  client_id: string;
};

/** @internal */
export const OauthTokenRequest$outboundSchema: z.ZodMiniType<
  OauthTokenRequest$Outbound,
  OauthTokenRequest
> = z.pipe(
  z.object({
    grantType: GrantType$outboundSchema,
    code: z.optional(z.string()),
    redirectUri: z.optional(z.string()),
    codeVerifier: z.optional(z.string()),
    refreshToken: z.optional(z.string()),
    clientId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      grantType: "grant_type",
      redirectUri: "redirect_uri",
      codeVerifier: "code_verifier",
      refreshToken: "refresh_token",
      clientId: "client_id",
    });
  }),
);

export function oauthTokenRequestToJSON(
  oauthTokenRequest: OauthTokenRequest,
): string {
  return JSON.stringify(
    OauthTokenRequest$outboundSchema.parse(oauthTokenRequest),
  );
}

/** @internal */
export const TokenType$inboundSchema: z.ZodMiniEnum<typeof TokenType> = z.enum(
  TokenType,
);

/** @internal */
export const OauthTokenResponse$inboundSchema: z.ZodMiniType<
  OauthTokenResponse,
  unknown
> = z.pipe(
  z.object({
    access_token: types.string(),
    token_type: TokenType$inboundSchema,
    expires_in: types.number(),
    refresh_token: z.optional(z.nullable(types.string())),
    scope: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "access_token": "accessToken",
      "token_type": "tokenType",
      "expires_in": "expiresIn",
      "refresh_token": "refreshToken",
    });
  }),
);

export function oauthTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<OauthTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OauthTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OauthTokenResponse' from JSON`,
  );
}
