/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type RenderCardRequest = {
  id: string;
};

/**
 * Card + rendered inputs
 */
export type RenderCardResponse = {
  card: { [k: string]: any };
  rendered: { [k: string]: any };
};

/** @internal */
export type RenderCardRequest$Outbound = {
  id: string;
};

/** @internal */
export const RenderCardRequest$outboundSchema: z.ZodMiniType<
  RenderCardRequest$Outbound,
  RenderCardRequest
> = z.object({
  id: z.string(),
});

export function renderCardRequestToJSON(
  renderCardRequest: RenderCardRequest,
): string {
  return JSON.stringify(
    RenderCardRequest$outboundSchema.parse(renderCardRequest),
  );
}

/** @internal */
export const RenderCardResponse$inboundSchema: z.ZodMiniType<
  RenderCardResponse,
  unknown
> = z.object({
  card: z.record(z.string(), z.any()),
  rendered: z.record(z.string(), z.any()),
});

export function renderCardResponseFromJSON(
  jsonString: string,
): SafeParseResult<RenderCardResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RenderCardResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RenderCardResponse' from JSON`,
  );
}
