/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type RotateApiKeyRequest = {
  id: string;
};

/**
 * Rotated key
 */
export type RotateApiKeyResponse = {
  newKey: string;
  newKeyId: string;
  oldExpiresAt?: Date | null | undefined;
};

/** @internal */
export type RotateApiKeyRequest$Outbound = {
  id: string;
};

/** @internal */
export const RotateApiKeyRequest$outboundSchema: z.ZodMiniType<
  RotateApiKeyRequest$Outbound,
  RotateApiKeyRequest
> = z.object({
  id: z.string(),
});

export function rotateApiKeyRequestToJSON(
  rotateApiKeyRequest: RotateApiKeyRequest,
): string {
  return JSON.stringify(
    RotateApiKeyRequest$outboundSchema.parse(rotateApiKeyRequest),
  );
}

/** @internal */
export const RotateApiKeyResponse$inboundSchema: z.ZodMiniType<
  RotateApiKeyResponse,
  unknown
> = z.pipe(
  z.object({
    new_key: types.string(),
    new_key_id: types.string(),
    old_expires_at: z.optional(z.nullable(types.date())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "new_key": "newKey",
      "new_key_id": "newKeyId",
      "old_expires_at": "oldExpiresAt",
    });
  }),
);

export function rotateApiKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<RotateApiKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RotateApiKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RotateApiKeyResponse' from JSON`,
  );
}
