/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SearchCardsRequest = {
  q: string;
  limit?: number | undefined;
  cardType?: string | undefined;
  minSimilarity?: number | undefined;
};

export type Item = {
  id: string;
  cardType: string;
  name: string;
  description?: string | null | undefined;
  previewUrl?: string | null | undefined;
  thumbUrl?: string | null | undefined;
  similarity: number;
  createdAt: Date;
};

/**
 * Search results
 */
export type SearchCardsResponse = {
  items: Array<Item>;
  total: number;
  queryTokens?: number | undefined;
  queryDocChars?: number | undefined;
};

/** @internal */
export type SearchCardsRequest$Outbound = {
  q: string;
  limit: number;
  card_type?: string | undefined;
  min_similarity: number;
};

/** @internal */
export const SearchCardsRequest$outboundSchema: z.ZodMiniType<
  SearchCardsRequest$Outbound,
  SearchCardsRequest
> = z.pipe(
  z.object({
    q: z.string(),
    limit: z._default(z.int(), 20),
    cardType: z.optional(z.string()),
    minSimilarity: z._default(z.number(), 0),
  }),
  z.transform((v) => {
    return remap$(v, {
      cardType: "card_type",
      minSimilarity: "min_similarity",
    });
  }),
);

export function searchCardsRequestToJSON(
  searchCardsRequest: SearchCardsRequest,
): string {
  return JSON.stringify(
    SearchCardsRequest$outboundSchema.parse(searchCardsRequest),
  );
}

/** @internal */
export const Item$inboundSchema: z.ZodMiniType<Item, unknown> = z.pipe(
  z.object({
    id: types.string(),
    card_type: types.string(),
    name: types.string(),
    description: z.optional(z.nullable(types.string())),
    preview_url: z.optional(z.nullable(types.string())),
    thumb_url: z.optional(z.nullable(types.string())),
    similarity: types.number(),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "card_type": "cardType",
      "preview_url": "previewUrl",
      "thumb_url": "thumbUrl",
      "created_at": "createdAt",
    });
  }),
);

export function itemFromJSON(
  jsonString: string,
): SafeParseResult<Item, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item' from JSON`,
  );
}

/** @internal */
export const SearchCardsResponse$inboundSchema: z.ZodMiniType<
  SearchCardsResponse,
  unknown
> = z.pipe(
  z.object({
    items: z.array(z.lazy(() => Item$inboundSchema)),
    total: types.number(),
    query_tokens: types.optional(types.number()),
    query_doc_chars: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "query_tokens": "queryTokens",
      "query_doc_chars": "queryDocChars",
    });
  }),
);

export function searchCardsResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchCardsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchCardsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchCardsResponse' from JSON`,
  );
}
