/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type TopUpWalletRequest = {
  amountUsd: number;
  paymentMethodId?: string | undefined;
};

/**
 * PaymentIntent created
 */
export type TopUpWalletResponse = {
  paymentIntentId: string;
  clientSecret?: string | null | undefined;
  status: string;
  amountUsd: number;
  nextAction?: { [k: string]: any } | null | undefined;
};

/** @internal */
export type TopUpWalletRequest$Outbound = {
  amount_usd: number;
  payment_method_id?: string | undefined;
};

/** @internal */
export const TopUpWalletRequest$outboundSchema: z.ZodMiniType<
  TopUpWalletRequest$Outbound,
  TopUpWalletRequest
> = z.pipe(
  z.object({
    amountUsd: z.number(),
    paymentMethodId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      amountUsd: "amount_usd",
      paymentMethodId: "payment_method_id",
    });
  }),
);

export function topUpWalletRequestToJSON(
  topUpWalletRequest: TopUpWalletRequest,
): string {
  return JSON.stringify(
    TopUpWalletRequest$outboundSchema.parse(topUpWalletRequest),
  );
}

/** @internal */
export const TopUpWalletResponse$inboundSchema: z.ZodMiniType<
  TopUpWalletResponse,
  unknown
> = z.pipe(
  z.object({
    payment_intent_id: types.string(),
    client_secret: z.optional(z.nullable(types.string())),
    status: types.string(),
    amount_usd: types.number(),
    next_action: z.optional(z.nullable(z.record(z.string(), z.any()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "payment_intent_id": "paymentIntentId",
      "client_secret": "clientSecret",
      "amount_usd": "amountUsd",
      "next_action": "nextAction",
    });
  }),
);

export function topUpWalletResponseFromJSON(
  jsonString: string,
): SafeParseResult<TopUpWalletResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TopUpWalletResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TopUpWalletResponse' from JSON`,
  );
}
