/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const CharacterStatus = {
  Training: "training",
  Ready: "ready",
  Failed: "failed",
} as const;
export type CharacterStatus = OpenEnum<typeof CharacterStatus>;

export type Character = {
  id: string;
  name: string;
  status: CharacterStatus;
  imageUrls?: Array<string> | undefined;
  attributes?: { [k: string]: any } | undefined;
  voiceId?: string | null | undefined;
  createdAt: Date;
};

/** @internal */
export const CharacterStatus$inboundSchema: z.ZodMiniType<
  CharacterStatus,
  unknown
> = openEnums.inboundSchema(CharacterStatus);

/** @internal */
export const Character$inboundSchema: z.ZodMiniType<Character, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      name: types.string(),
      status: CharacterStatus$inboundSchema,
      image_urls: types.optional(z.array(types.string())),
      attributes: types.optional(z.record(z.string(), z.any())),
      voice_id: z.optional(z.nullable(types.string())),
      created_at: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "image_urls": "imageUrls",
        "voice_id": "voiceId",
        "created_at": "createdAt",
      });
    }),
  );

export function characterFromJSON(
  jsonString: string,
): SafeParseResult<Character, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Character$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Character' from JSON`,
  );
}
