/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Discriminator. Always `compose` for this endpoint.
 */
export const ComposeJobAckType = {
  Compose: "compose",
} as const;
/**
 * Discriminator. Always `compose` for this endpoint.
 */
export type ComposeJobAckType = ClosedEnum<typeof ComposeJobAckType>;

/**
 * Initial status. The job advances to `running` and then a terminal state asynchronously.
 */
export const ComposeJobAckStatus = {
  Queued: "queued",
} as const;
/**
 * Initial status. The job advances to `running` and then a terminal state asynchronously.
 */
export type ComposeJobAckStatus = ClosedEnum<typeof ComposeJobAckStatus>;

/**
 * Cost-spine operation id used to price this job.
 */
export const OperationId = {
  ComposeStitchPerMinute: "compose.stitch_per_minute",
} as const;
/**
 * Cost-spine operation id used to price this job.
 */
export type OperationId = ClosedEnum<typeof OperationId>;

/**
 * Acknowledgement returned by `POST /v1/compose` when a stitch job has
 *
 * @remarks
 * been queued. The job is asynchronous — clients poll
 * `GET /v1/jobs/{id}` (with the `id` returned here) for terminal
 * status and the stitched output URL.
 */
export type ComposeJobAck = {
  /**
   * Job id; pass to `GET /v1/jobs/{id}` to poll.
   */
  id: string;
  /**
   * Discriminator. Always `compose` for this endpoint.
   */
  type: ComposeJobAckType;
  /**
   * Initial status. The job advances to `running` and then a terminal state asynchronously.
   */
  status: ComposeJobAckStatus;
  /**
   * Cost-spine operation id used to price this job.
   */
  operationId: OperationId;
  /**
   * Reserved wallet amount in USD micros (`1 USD = 1_000_000`).
   */
  estimatedCostUsdMicros: number;
  /**
   * Reserved wallet amount in USD (convenience field; equals `estimated_cost_usd_micros / 1_000_000`).
   */
  estimatedCostUsd: number;
  createdAt: Date;
};

/** @internal */
export const ComposeJobAckType$inboundSchema: z.ZodMiniEnum<
  typeof ComposeJobAckType
> = z.enum(ComposeJobAckType);

/** @internal */
export const ComposeJobAckStatus$inboundSchema: z.ZodMiniEnum<
  typeof ComposeJobAckStatus
> = z.enum(ComposeJobAckStatus);

/** @internal */
export const OperationId$inboundSchema: z.ZodMiniEnum<typeof OperationId> = z
  .enum(OperationId);

/** @internal */
export const ComposeJobAck$inboundSchema: z.ZodMiniType<
  ComposeJobAck,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    type: ComposeJobAckType$inboundSchema,
    status: ComposeJobAckStatus$inboundSchema,
    operation_id: OperationId$inboundSchema,
    estimated_cost_usd_micros: types.number(),
    estimated_cost_usd: types.number(),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "operation_id": "operationId",
      "estimated_cost_usd_micros": "estimatedCostUsdMicros",
      "estimated_cost_usd": "estimatedCostUsd",
      "created_at": "createdAt",
    });
  }),
);

export function composeJobAckFromJSON(
  jsonString: string,
): SafeParseResult<ComposeJobAck, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ComposeJobAck$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ComposeJobAck' from JSON`,
  );
}
