/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export type Segment = {
  assetId: string;
  startTime: number;
  duration: number;
  effects?: { [k: string]: any } | undefined;
};

export const OutputFormat = {
  Mp4: "mp4",
  Webm: "webm",
} as const;
export type OutputFormat = ClosedEnum<typeof OutputFormat>;

export type ComposeRequest = {
  segments: Array<Segment>;
  outputResolution?: string | undefined;
  outputFormat?: OutputFormat | undefined;
};

/** @internal */
export type Segment$Outbound = {
  asset_id: string;
  start_time: number;
  duration: number;
  effects?: { [k: string]: any } | undefined;
};

/** @internal */
export const Segment$outboundSchema: z.ZodMiniType<Segment$Outbound, Segment> =
  z.pipe(
    z.object({
      assetId: z.string(),
      startTime: z.number(),
      duration: z.number(),
      effects: z.optional(z.record(z.string(), z.any())),
    }),
    z.transform((v) => {
      return remap$(v, {
        assetId: "asset_id",
        startTime: "start_time",
      });
    }),
  );

export function segmentToJSON(segment: Segment): string {
  return JSON.stringify(Segment$outboundSchema.parse(segment));
}

/** @internal */
export const OutputFormat$outboundSchema: z.ZodMiniEnum<typeof OutputFormat> = z
  .enum(OutputFormat);

/** @internal */
export type ComposeRequest$Outbound = {
  segments: Array<Segment$Outbound>;
  output_resolution: string;
  output_format: string;
};

/** @internal */
export const ComposeRequest$outboundSchema: z.ZodMiniType<
  ComposeRequest$Outbound,
  ComposeRequest
> = z.pipe(
  z.object({
    segments: z.array(z.lazy(() => Segment$outboundSchema)),
    outputResolution: z._default(z.string(), "1080p"),
    outputFormat: z._default(OutputFormat$outboundSchema, "mp4"),
  }),
  z.transform((v) => {
    return remap$(v, {
      outputResolution: "output_resolution",
      outputFormat: "output_format",
    });
  }),
);

export function composeRequestToJSON(composeRequest: ComposeRequest): string {
  return JSON.stringify(ComposeRequest$outboundSchema.parse(composeRequest));
}
