/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export const AspectRatio = {
  Eleven: "1:1",
  OneHundredAndSixtyNine: "16:9",
  NineHundredAndSixteen: "9:16",
  FortyThree: "4:3",
  ThirtyFour: "3:4",
} as const;
export type AspectRatio = ClosedEnum<typeof AspectRatio>;

export type Lora = {
  path: string;
  scale: number;
};

export type GenerateImageRequest = {
  model: string;
  prompt: string;
  negativePrompt?: string | undefined;
  aspectRatio?: AspectRatio | undefined;
  resolution?: string | undefined;
  seedImageUrl?: string | undefined;
  loras?: Array<Lora> | undefined;
  seed?: number | undefined;
  characterId?: string | undefined;
  prismId?: string | undefined;
};

/** @internal */
export const AspectRatio$outboundSchema: z.ZodMiniEnum<typeof AspectRatio> = z
  .enum(AspectRatio);

/** @internal */
export type Lora$Outbound = {
  path: string;
  scale: number;
};

/** @internal */
export const Lora$outboundSchema: z.ZodMiniType<Lora$Outbound, Lora> = z.object(
  {
    path: z.string(),
    scale: z.number(),
  },
);

export function loraToJSON(lora: Lora): string {
  return JSON.stringify(Lora$outboundSchema.parse(lora));
}

/** @internal */
export type GenerateImageRequest$Outbound = {
  model: string;
  prompt: string;
  negative_prompt?: string | undefined;
  aspect_ratio?: string | undefined;
  resolution?: string | undefined;
  seed_image_url?: string | undefined;
  loras?: Array<Lora$Outbound> | undefined;
  seed?: number | undefined;
  character_id?: string | undefined;
  prism_id?: string | undefined;
};

/** @internal */
export const GenerateImageRequest$outboundSchema: z.ZodMiniType<
  GenerateImageRequest$Outbound,
  GenerateImageRequest
> = z.pipe(
  z.object({
    model: z.string(),
    prompt: z.string(),
    negativePrompt: z.optional(z.string()),
    aspectRatio: z.optional(AspectRatio$outboundSchema),
    resolution: z.optional(z.string()),
    seedImageUrl: z.optional(z.string()),
    loras: z.optional(z.array(z.lazy(() => Lora$outboundSchema))),
    seed: z.optional(z.int()),
    characterId: z.optional(z.string()),
    prismId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      negativePrompt: "negative_prompt",
      aspectRatio: "aspect_ratio",
      seedImageUrl: "seed_image_url",
      characterId: "character_id",
      prismId: "prism_id",
    });
  }),
);

export function generateImageRequestToJSON(
  generateImageRequest: GenerateImageRequest,
): string {
  return JSON.stringify(
    GenerateImageRequest$outboundSchema.parse(generateImageRequest),
  );
}
