/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type GenerateVideoRequest = {
  model: string;
  prompt: string;
  imageUrl?: string | undefined;
  durationS?: number | undefined;
  withAudio?: boolean | undefined;
  motionId?: string | undefined;
  characterId?: string | undefined;
  prismId?: string | undefined;
};

/** @internal */
export type GenerateVideoRequest$Outbound = {
  model: string;
  prompt: string;
  image_url?: string | undefined;
  duration_s?: number | undefined;
  with_audio: boolean;
  motion_id?: string | undefined;
  character_id?: string | undefined;
  prism_id?: string | undefined;
};

/** @internal */
export const GenerateVideoRequest$outboundSchema: z.ZodMiniType<
  GenerateVideoRequest$Outbound,
  GenerateVideoRequest
> = z.pipe(
  z.object({
    model: z.string(),
    prompt: z.string(),
    imageUrl: z.optional(z.string()),
    durationS: z.optional(z.int()),
    withAudio: z._default(z.boolean(), false),
    motionId: z.optional(z.string()),
    characterId: z.optional(z.string()),
    prismId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      imageUrl: "image_url",
      durationS: "duration_s",
      withAudio: "with_audio",
      motionId: "motion_id",
      characterId: "character_id",
      prismId: "prism_id",
    });
  }),
);

export function generateVideoRequestToJSON(
  generateVideoRequest: GenerateVideoRequest,
): string {
  return JSON.stringify(
    GenerateVideoRequest$outboundSchema.parse(generateVideoRequest),
  );
}
