/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type PhonemeOverride = {
  from: string;
  to: string;
};

export type GenerateAudioRequest = {
  text: string;
  voiceId?: string | undefined;
  characterVoiceId?: string | undefined;
  model?: string | undefined;
  phonemeOverrides?: Array<PhonemeOverride> | undefined;
};

/** @internal */
export type PhonemeOverride$Outbound = {
  from: string;
  to: string;
};

/** @internal */
export const PhonemeOverride$outboundSchema: z.ZodMiniType<
  PhonemeOverride$Outbound,
  PhonemeOverride
> = z.object({
  from: z.string(),
  to: z.string(),
});

export function phonemeOverrideToJSON(
  phonemeOverride: PhonemeOverride,
): string {
  return JSON.stringify(PhonemeOverride$outboundSchema.parse(phonemeOverride));
}

/** @internal */
export type GenerateAudioRequest$Outbound = {
  text: string;
  voice_id?: string | undefined;
  character_voice_id?: string | undefined;
  model?: string | undefined;
  phoneme_overrides?: Array<PhonemeOverride$Outbound> | undefined;
};

/** @internal */
export const GenerateAudioRequest$outboundSchema: z.ZodMiniType<
  GenerateAudioRequest$Outbound,
  GenerateAudioRequest
> = z.pipe(
  z.object({
    text: z.string(),
    voiceId: z.optional(z.string()),
    characterVoiceId: z.optional(z.string()),
    model: z.optional(z.string()),
    phonemeOverrides: z.optional(
      z.array(z.lazy(() => PhonemeOverride$outboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      voiceId: "voice_id",
      characterVoiceId: "character_voice_id",
      phonemeOverrides: "phoneme_overrides",
    });
  }),
);

export function generateAudioRequestToJSON(
  generateAudioRequest: GenerateAudioRequest,
): string {
  return JSON.stringify(
    GenerateAudioRequest$outboundSchema.parse(generateAudioRequest),
  );
}
