/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const JobType = {
  Image: "image",
  Video: "video",
  Audio: "audio",
  Compose: "compose",
  CharacterTrain: "character_train",
  PrismApply: "prism_apply",
} as const;
export type JobType = OpenEnum<typeof JobType>;

export const JobStatus = {
  Queued: "queued",
  Running: "running",
  Completed: "completed",
  Failed: "failed",
  Cancelled: "cancelled",
  NsfwBlocked: "nsfw_blocked",
} as const;
export type JobStatus = OpenEnum<typeof JobStatus>;

export type JobErrorError = {
  code: string;
  message?: string | undefined;
  details?: { [k: string]: any } | undefined;
};

export type JobError = {
  error: JobErrorError;
};

export type Job = {
  jobId: string;
  type: JobType;
  status: JobStatus;
  progressPct?: number | null | undefined;
  estimatedCostUsd?: number | null | undefined;
  chargedCostUsd?: number | null | undefined;
  outputUrls?: Array<string> | null | undefined;
  error?: JobError | null | undefined;
  createdAt: Date;
  completedAt?: Date | null | undefined;
  /**
   * Present only when `type=prism_apply`. Identifies the prism that was applied.
   */
  prismId?: string | undefined;
};

/** @internal */
export const JobType$inboundSchema: z.ZodMiniType<JobType, unknown> = openEnums
  .inboundSchema(JobType);

/** @internal */
export const JobStatus$inboundSchema: z.ZodMiniType<JobStatus, unknown> =
  openEnums.inboundSchema(JobStatus);

/** @internal */
export const JobErrorError$inboundSchema: z.ZodMiniType<
  JobErrorError,
  unknown
> = z.object({
  code: types.string(),
  message: types.optional(types.string()),
  details: types.optional(z.record(z.string(), z.any())),
});

export function jobErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<JobErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JobErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JobErrorError' from JSON`,
  );
}

/** @internal */
export const JobError$inboundSchema: z.ZodMiniType<JobError, unknown> = z
  .object({
    error: z.lazy(() => JobErrorError$inboundSchema),
  });

export function jobErrorFromJSON(
  jsonString: string,
): SafeParseResult<JobError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JobError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JobError' from JSON`,
  );
}

/** @internal */
export const Job$inboundSchema: z.ZodMiniType<Job, unknown> = z.pipe(
  z.object({
    job_id: types.string(),
    type: JobType$inboundSchema,
    status: JobStatus$inboundSchema,
    progress_pct: z.optional(z.nullable(types.number())),
    estimated_cost_usd: z.optional(z.nullable(types.number())),
    charged_cost_usd: z.optional(z.nullable(types.number())),
    output_urls: z.optional(z.nullable(z.array(types.string()))),
    error: z.optional(z.nullable(z.lazy(() => JobError$inboundSchema))),
    created_at: types.date(),
    completed_at: z.optional(z.nullable(types.date())),
    prism_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "job_id": "jobId",
      "progress_pct": "progressPct",
      "estimated_cost_usd": "estimatedCostUsd",
      "charged_cost_usd": "chargedCostUsd",
      "output_urls": "outputUrls",
      "created_at": "createdAt",
      "completed_at": "completedAt",
      "prism_id": "prismId",
    });
  }),
);

export function jobFromJSON(
  jsonString: string,
): SafeParseResult<Job, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Job$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Job' from JSON`,
  );
}
