/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ModelType = {
  Image: "image",
  Video: "video",
  Audio: "audio",
  Compose: "compose",
  Training: "training",
  Prism: "prism",
} as const;
export type ModelType = OpenEnum<typeof ModelType>;

export type Model = {
  modelId: string;
  type: ModelType;
  provider: string;
  maxResolution?: string | null | undefined;
  maxDurationS?: number | null | undefined;
  supportsAudio?: boolean | undefined;
  costUsdPerUnit: number;
  unit: string;
};

/** @internal */
export const ModelType$inboundSchema: z.ZodMiniType<ModelType, unknown> =
  openEnums.inboundSchema(ModelType);

/** @internal */
export const Model$inboundSchema: z.ZodMiniType<Model, unknown> = z.pipe(
  z.object({
    model_id: types.string(),
    type: ModelType$inboundSchema,
    provider: types.string(),
    max_resolution: z.optional(z.nullable(types.string())),
    max_duration_s: z.optional(z.nullable(types.number())),
    supports_audio: types.optional(types.boolean()),
    cost_usd_per_unit: types.number(),
    unit: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "model_id": "modelId",
      "max_resolution": "maxResolution",
      "max_duration_s": "maxDurationS",
      "supports_audio": "supportsAudio",
      "cost_usd_per_unit": "costUsdPerUnit",
    });
  }),
);

export function modelFromJSON(
  jsonString: string,
): SafeParseResult<Model, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Model$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Model' from JSON`,
  );
}
