/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const CompatibleWith = {
  Image: "image",
  Video: "video",
  Audio: "audio",
} as const;
export type CompatibleWith = OpenEnum<typeof CompatibleWith>;

export type Prism = {
  id: string;
  name: string;
  description?: string | undefined;
  category: string;
  compatibleWith: Array<CompatibleWith>;
  previewUrl?: string | undefined;
};

/** @internal */
export const CompatibleWith$inboundSchema: z.ZodMiniType<
  CompatibleWith,
  unknown
> = openEnums.inboundSchema(CompatibleWith);

/** @internal */
export const Prism$inboundSchema: z.ZodMiniType<Prism, unknown> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    description: types.optional(types.string()),
    category: types.string(),
    compatible_with: z.array(CompatibleWith$inboundSchema),
    preview_url: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "compatible_with": "compatibleWith",
      "preview_url": "previewUrl",
    });
  }),
);

export function prismFromJSON(
  jsonString: string,
): SafeParseResult<Prism, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Prism$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Prism' from JSON`,
  );
}
